hxl:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    #其余配置分散
    host: 192.168.154.128
    port: 3306
    database: sky_take_out

# 布隆过滤器配置
bloom-filter:
  expected-insertions: 100000  # 期望插入的元素数量
  fpp: 0.03  # 误判率