server:
  port: 8080
  servlet:
    context-path: / #项目根路径

# 日志配置
logging:
  # 配置各包路径的日志级别
  level:
    com:
      sky:
        # Mapper层(数据访问层)使用DEBUG级别，会输出SQL语句和参数等详细信息
        mapper: debug
        # Service层(业务逻辑层)使用INFO级别，输出关键业务操作信息
        service: info
        # Controller层(控制器层)使用INFO级别，输出请求处理的关键信息
        controller: info

spring:
  profiles:
    #动态激活的yaml配置
    active: dev, aliOssInfo, redisInfo, weChatInfo
  main:
    allow-circular-references: true

  #配置连接池信息
  datasource:
    druid:
      driver-class-name: ${hxl.datasource.driver-class-name}
      username: ${hxl.datasource.username}
      password: ${hxl.datasource.password}
      url: jdbc:mysql://${hxl.datasource.host}:${hxl.datasource.port}/${hxl.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  #指定单个文件上传的大小
  servlet:
    multipart:
      max-file-size: 2MB
  #redis相关配置
  redis:
    # Redis 密码，用于认证连接 默认连接0号数据库  共0~15
    password: ${redis.password}

    # Redis 集群配置
    cluster:
      # 集群节点列表，格式为 host:port
      nodes:
        - ${redis.cluster.nodes[0]}
        - ${redis.cluster.nodes[1]}
        - ${redis.cluster.nodes[2]}
        - ${redis.cluster.nodes[3]}
        - ${redis.cluster.nodes[4]}
        - ${redis.cluster.nodes[5]}

      # 最大重定向次数，用于处理 MOVED/ASK 错误
      max-redirects: 3

    # Lettuce 连接池配置优化 可以不用写
    lettuce:
      cluster:
        refresh:
          adaptive: true #支持集群拓扑动态感应刷新
          period: 2000 #设置2s刷新一次
      pool:
        # 连接池最大活跃连接数
        max-active: 8
        # 连接池最大等待时间（负数表示无限等待）
        max-wait: -1ms
        # 连接池最大空闲连接数
        max-idle: 8
        # 连接池最小空闲连接数
        min-idle: 0


#MyBatis配置 设置xml文件的扫描包路径
mybatis:
  #mapper配置文件 扫描 当前文件路径下的mapper包下的所有xml文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hxl.entity # 给路径下的 pojo包 里的实体类 起别名
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

#配置jwt令牌校验(管理端和用户端)
hxl:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: HxlAndJsj
    # 设置jwt过期时间 设置为30天左右
    admin-ttl: 2600000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    #微信用户端的 jwt
    user-secret-key: HxlAndJsj
    user-ttl: 2600000000
    user-token-name: authentication
  #阿里Oss相关配置
  alioss:
    endpoint: ${hxl.alioss.endpoint}
    access-key-id: ${hxl.alioss.access-key-id}
    access-key-secret: ${hxl.alioss.access-key-secret}
    bucket-name: ${hxl.alioss.bucket-name}

  #微信小程序
  wechat:
    appid: ${hxl.wechat.appid}
    secret: ${hxl.wechat.secret}